[package]
name = "lux"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'

[unstable]
build-std = ["core", "alloc"]

[features]

[dependencies]
libc = "*"